import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const read = (path) => readFile(new URL(`../${path}`, import.meta.url), "utf8");

test("publisher exposes local public URLs and keeps empty result panels hidden", async () => {
  const [server, launcher, packageJson, envExample, html, app, css] = await Promise.all([
    read("server.js"),
    read("dev.js"),
    read("package.json"),
    read(".env.example"),
    read("public/index.html"),
    read("public/app.js"),
    read("public/styles.css"),
  ]);

  assert.match(server, /function publicContentUrl/);
  assert.match(server, /function previewContentUrl/);
  assert.match(server, /if \(preview\) return `\/preview\/articles\/\$\{contentId\}`/);
  assert.match(server, /return `\/\$\{contentId\}`/);
  assert.match(server, /function createArticleTitleSuggestions/);
  assert.match(server, /\/api\/ai\/article-title-suggestions/);
  assert.match(server, /\/api\/recommendations/);
  assert.match(server, /\/api\/recommendation-publications/);
  assert.match(server, /refreshRecommendationManifest/);
  assert.match(server, /sanitizeArticleTitleSuggestions/);
  assert.match(server, /allocateContentId/);
  assert.match(server, /contentId: \$\{yamlString\(payload\.contentId\)\}/);
  assert.match(server, /publicUrl: publicContentUrl/);
  assert.match(server, /previewUrl: previewContentUrl/);
  assert.match(server, /"cache-control": "no-store"/);
  assert.match(server, /http:\/\/127\.0\.0\.1:4321/);
  assert.doesNotMatch(server, /XGIF_SITE_URL/);
  assert.doesNotMatch(envExample, /XGIF_SITE_URL/);
  assert.match(packageJson, /"dev": "node dev\.js start"/);
  assert.match(packageJson, /"start": "node dev\.js start"/);
  assert.match(packageJson, /"stop": "node dev\.js stop"/);
  assert.match(packageJson, /"restart": "node dev\.js restart"/);
  assert.match(packageJson, /"status": "node dev\.js status"/);
  assert.match(packageJson, /"doctor": "node dev\.js doctor"/);
  assert.match(packageJson, /"start:publisher": "node --disable-warning=ExperimentalWarning server\.js"/);
  assert.match(launcher, /Astro 站点预览/);
  assert.match(launcher, /detached: true/);
  assert.match(launcher, /\.runtime/);
  assert.match(launcher, /async function waitFor/);
  assert.match(launcher, /publisherStatusUrl/);
  assert.match(launcher, /async function refreshPublisherStatus/);
  assert.match(launcher, /async function doctor/);
  assert.match(launcher, /publisherPidManaged/);
  assert.match(launcher, /--host", "127\.0\.0\.1", "--port", "4321"/);
  assert.match(html, /id="publisher-service"/);
  assert.match(html, /id="site-preview-service"/);
  assert.match(html, /id="publisher-health"/);
  assert.match(html, /id="publisher-health-label"/);
  assert.match(html, /id="open-site-preview"/);
  assert.match(html, /id="recommendation-publish"/);
  assert.match(html, /id="app-frame"/);
  assert.match(html, /id="workspace-sidebar"/);
  assert.match(html, /class="workspace-navigation"/);
  assert.doesNotMatch(html, /id="workspace-nav-toggle"/);
  assert.doesNotMatch(html, /id="workspace-nav-close"/);
  assert.doesNotMatch(html, /id="workspace-nav-scrim"/);
  assert.match(html, /id="workspace-page-title"/);
  assert.doesNotMatch(html, /data-tab="audit"/);
  assert.doesNotMatch(html, /data-nav-action="trash"/);
  assert.doesNotMatch(html, /id="sidebar-trash-count"/);
  assert.match(html, /data-tab="system"/);
  assert.doesNotMatch(html, /data-nav-action="site-preview"/);
  assert.equal((html.match(/class="tab(?: active)?"/g) || []).length, 5);
  assert.match(html, /class="workspace-create-menu"/);
  assert.match(html, /class="tab active" data-tab="library"/);
  assert.doesNotMatch(html, /class="tabs"/);
  assert.match(html, /id="library-open"/);
  assert.match(html, /id="library-preview"/);
  assert.match(html, /id="library-result" hidden/);
  assert.match(html, /class="library-status-tabs"/);
  assert.match(html, /id="library-task-banner"/);
  assert.doesNotMatch(html, /id="library-task-action"/);
  assert.match(html, /id="library-batch-toggle"/);
  assert.match(html, /id="library-feedback" hidden role="status" aria-live="polite"/);
  assert.match(html, /styles\.css\?v=20260729-publication-facts-1/);
  assert.match(html, /app\.js\?v=20260729-publication-facts-1/);
  assert.match(html, /data-library-status="draft"/);
  assert.match(html, /data-library-status="local"/);
  assert.match(html, /data-library-status="cloud"/);
  assert.doesNotMatch(html, /data-library-status="pending"/);
  assert.doesNotMatch(html, /data-library-status="unknown"/);
  assert.doesNotMatch(html, /data-library-status="online"/);
  assert.doesNotMatch(html, /data-library-status="pending_commit"/);
  assert.match(html, /data-library-view="compact"/);
  assert.match(html, /id="library-pagination"/);
  assert.match(html, /id="library-bulk-publish"/);
  assert.match(html, /id="batch-publish-dialog"/);
  assert.match(html, /id="batch-publish-review-confirmed"/);
  assert.match(html, /id="library-bulk-draft"/);
  assert.match(html, /id="library-bulk-edit"/);
  assert.match(html, /id="library-bulk-sync"/);
  assert.match(html, /id="library-sync-current"/);
  assert.match(html, /id="library-bulk-trash"/);
  assert.match(html, /id="library-select-filtered"/);
  assert.match(html, /id="library-page-size"/);
  assert.match(html, /id="batch-edit-dialog"/);
  assert.match(html, /id="library-undo-trash"/);
  assert.match(html, /id="library-open-trash"/);
  assert.match(html, /id="content-sync-summary"/);
  assert.match(html, /id="open-pending-content"/);
  assert.match(html, /id="library-inspector" hidden/);
  assert.match(html, /id="library-close-detail"/);
  assert.match(html, /id="library-duplicate"/);
  assert.match(html, /id="library-return-draft"/);
  assert.match(html, /在站点预览中查看 ↗/);
  assert.match(html, /class="library-detail-more"/);
  assert.match(html, /class="library-more-actions"/);
  assert.match(html, /id="trash-dialog"/);
  assert.match(html, /id="trash-select-all"/);
  assert.match(html, /id="trash-restore-selected"/);
  assert.match(html, /id="trash-purge-selected"/);
  assert.match(html, /id="storage-backup"/);
  assert.match(html, /id="library-audit"/);
  assert.match(html, /id="audit-panel"/);
  assert.doesNotMatch(html, /id="content-audit-dialog"/);
  assert.match(html, /id="tag-governance-list"/);
  assert.match(html, /id="tag-merge-preview"/);
  assert.match(html, /id="article-open-assets"/);
  assert.match(html, /id="asset-library-dialog"/);
  assert.match(html, /id="recovery-dashboard-grid"/);
  assert.match(html, /id="system-run-recovery"/);
  assert.match(html, /id="connection-public-git"/);
  assert.match(html, /id="connection-private-git"/);
  assert.match(html, /id="private-content-sync"/);
  assert.match(html, /id="article-cover-assets"/);
  assert.match(html, /<option value="unknown">来源待确认<\/option>/);
  assert.match(html, /<option value="publication">外部来源<\/option>/);
  assert.doesNotMatch(html, /<option value="editorial">/);
  assert.match(html, /<input name="editorNote" type="hidden" \/>/);
  assert.doesNotMatch(html, />\s*公开编辑手记\s*</);
  assert.match(html, /没有具体原文可留空/);
  assert.match(html, /没有原文链接也能正常发布/);
  assert.doesNotMatch(app, /\["title", "summary", "tags", "readTime", "editorNote", "source"\]/);
  assert.match(app, /data\?\.sourceKind === "editorial"/);
  assert.match(server, /发布后会明确显示“来源待确认”/);
  assert.doesNotMatch(server, /文章来源仍待确认，只能保存为草稿/);
  assert.match(html, /data-tab="sync"/);
  assert.match(html, /id="sync-navigation-count"/);
  assert.match(html, /id="sync-panel"/);
  assert.match(html, /id="sync-all-local"/);
  assert.match(html, /id="sync-queue-list"/);
  assert.match(html, /id="sync-pr-link"/);
  assert.doesNotMatch(html, /data-system-view="sync"/);
  assert.match(html, /id="sync-history-list"/);
  assert.doesNotMatch(html, /id="sync-history-dialog"/);
  assert.match(html, /aria-label="内容类型"/);
  assert.match(html, /aria-label="排序方式"/);
  assert.equal((html.match(/name="publishMode"/g) || []).length, 4);
  assert.match(html, /data-open-details="article"/);
  assert.match(html, /data-open-details="image"/);
  assert.match(html, /class="article-workspace-toolbar"/);
  assert.match(html, /class="article-editor-canvas"/);
  assert.match(html, /class="article-inspector"/);
  assert.match(html, /data-article-inspector-tab="info"/);
  assert.match(html, /data-article-inspector-tab="cover"/);
  assert.match(html, /data-article-inspector-tab="preview"/);
  assert.doesNotMatch(html, /data-article-inspector-tab="source"/);
  assert.equal((html.match(/data-article-inspector-tab=/g) || []).length, 3);
  assert.match(html, /id="article-source-summary"/);
  assert.match(html, /data-article-inspector-open="source"/);
  assert.match(html, /id="article-source-details"/);
  assert.ok(html.indexOf('id="article-source-summary"') < html.indexOf('name="source" required'));
  assert.match(html, /id="article-info-tab-status"/);
  assert.match(html, /id="article-source-status"/);
  assert.match(html, /id="article-cover-tab-status"/);
  assert.match(html, /id="article-save-draft"/);
  assert.match(html, /id="article-real-preview" hidden disabled/);
  assert.match(html, /class="toolbar-more-menu"/);
  assert.match(html, /id="article-next-action"[^>]*>发布<\/button>/);
  assert.doesNotMatch(html, /id="article-next-action"[^>]*disabled/);
  assert.match(html, /id="article-read-time-display">1 分钟<\/output>/);
  assert.match(html, /name="readTime" type="hidden" value="1 分钟"/);
  assert.match(html, /id="article-cover-alt-field" hidden/);
  assert.match(html, /id="article-ai-review" aria-live="polite" hidden/);
  assert.doesNotMatch(html, /id="article-publish-journey"/);
  assert.doesNotMatch(html, /id="article-page-preview"/);
  assert.match(html, /id="article-ai-menu" hidden/);
  assert.match(html, /id="article-title-ai"/);
  assert.match(html, /data-ai-fill="article"/);
  assert.ok(html.indexOf('id="article-title"') < html.indexOf('id="article-title-ai"'));
  assert.ok(html.indexOf('data-ai-fill="article"') < html.indexOf('id="article-body"'));
  assert.match(html, /id="article-title-ai"/);
  assert.match(html, /id="article-title-suggestions"[^>]*hidden/);
  assert.match(html, /id="article-title-candidate-list"/);
  assert.match(html, /id="article-title-ai-status" role="status" aria-live="polite"/);
  assert.match(html, /id="article-result" hidden/);
  assert.match(html, /id="article-audit-guidance" hidden aria-live="polite"/);
  assert.match(html, /id="article-audit-issues"/);
  assert.match(html, /id="article-audit-next-step"/);
  assert.match(html, /class="markdown-toolbar"/);
  assert.match(html, /id="article-body-stats"/);
  assert.match(html, /id="article-outline"/);
  assert.match(html, /id="article-version-history"/);
  assert.match(html, /id="image-version-history"/);
  assert.match(html, /id="version-history-dialog"/);
  assert.match(html, /id="system-panel"/);
  assert.doesNotMatch(html, /id="open-system-status"/);
  assert.match(html, /<button class="publisher-health" id="publisher-health"/);
  assert.match(html, /class="network-disclosure"/);
  assert.doesNotMatch(html, /<h2>内容库<\/h2>/);
  assert.doesNotMatch(html, /<h2>内容体检与标签<\/h2>/);
  assert.doesNotMatch(html, /<h2>系统状态与恢复<\/h2>/);
  assert.match(html, /正文只在本机通过 SSH 隧道发送到 M4 Ollama/);
  assert.match(html, /id="recommendation-refresh"/);
  assert.match(html, /id="recommendation-result" role="status" aria-live="polite"/);
  assert.match(html, /id="article-next-action"/);
  assert.doesNotMatch(html, /id="article-next-step-title"/);
  assert.match(html, /class="library-tools-more"/);
  assert.match(html, /class="advanced-settings article-publishing-settings"/);
  assert.match(app, /articleNextAction\.dataset\.action = alreadyPublished && !dirty \? "sync" : "publish"/);
  assert.match(app, /imageNextAction\.dataset\.action = alreadyPublished && !dirty \? "sync" : "publish"/);
  assert.doesNotMatch(app, /image-advanced-summary/);
  assert.match(html, /class=\"editor image-workspace-form\"/);
  assert.match(html, /class=\"image-editor-canvas\"/);
  assert.match(html, /class=\"image-inspector\"/);
  assert.equal((html.match(/data-image-inspector-tab=/g) || []).length, 3);
  assert.match(html, /id=\"image-save-draft\"/);
  assert.match(html, /id=\"image-real-preview\" hidden disabled/);
  assert.match(html, /id=\"image-next-action\"[^>]*>发布<\/button>/);
  assert.match(html, /id=\"image-ai-review\" aria-live=\"polite\" hidden/);
  assert.match(html, /id=\"image-ai-availability\"/);
  assert.match(html, /name=\"ratio\" type=\"hidden\"/);
  assert.doesNotMatch(html, /<select name=\"ratio\">/);
  assert.doesNotMatch(html, /data-quality=/);
  assert.doesNotMatch(html, /name="commit"/);
  assert.doesNotMatch(html, /name="push"/);
  assert.match(html, /id="article-review-confirmation"/);
  assert.match(html, /已核对来源情况与正文，可公开发布/);
  assert.match(html, /name="internalReviewConfirmed" type="checkbox"/);
  assert.doesNotMatch(html, /<option value="unresolved">尚未完成<\/option>/);
  assert.doesNotMatch(html, /data-check="article"/);
  assert.doesNotMatch(html, /data-check="image"/);
  assert.match(app, /window\.open\(activeContent\.publicUrl/);
  assert.match(app, /window\.open\(activeContent\.previewUrl/);
  assert.match(app, /function syncPublishMode/);
  assert.match(app, /function syncInternalReviewState/);
  assert.match(app, /confirmationPanel\.hidden = !note\.value\.trim\(\)/);
  assert.match(app, /input\.name === "internalReviewConfirmed"/);
  assert.match(app, /function syncImageActionState/);
  assert.match(app, /function setImageInspectorTab/);
  assert.match(app, /function updateImageInspectorStatus/);
  assert.match(app, /imageNextAction\.addEventListener/);
  assert.match(app, /function renderArticleTitleSuggestions/);
  assert.match(app, /function applyArticleTitleSuggestion/);
  assert.match(app, /function invalidateArticleTitleSuggestions/);
  assert.match(app, /\/api\/ai\/article-title-suggestions/);
  assert.match(app, /function renderRecommendationStatus/);
  assert.match(app, /\/api\/recommendations/);
  assert.match(app, /OpenAI 兼容接口/);
  assert.doesNotMatch(app, /articleDetails\.open/);
  assert.doesNotMatch(app, /function setWorkspaceNavigationOpen/);
  assert.doesNotMatch(app, /function runWorkspaceNavigationAction/);
  assert.match(app, /function restoreWorkspaceRoute/);
  assert.match(app, /async function fetchPublisherStatus/);
  assert.match(app, /publisherStatusRequest/);
  assert.match(app, /window\.addEventListener\("popstate"/);
  assert.match(app, /function setSystemView/);
  assert.match(app, /function updateTrashCount/);
  assert.doesNotMatch(app, /workspaceNavToggle/);
  assert.match(app, /setAttribute\("aria-current", "page"\)/);
  assert.doesNotMatch(app, /workspace-open-site-preview/);
  assert.match(app, /function markFormDirty/);
  assert.match(app, /function markFormClean/);
  assert.match(app, /new AbortController\(\)/);
  assert.match(app, /function readDraftRevisions/);
  assert.match(app, /function restoreSavedVersion/);
  assert.match(app, /function applyMarkdownAction/);
  assert.match(app, /\/api\/assets\/upload/);
  assert.match(app, /\/api\/content\/duplicate/);
  assert.match(app, /\/api\/content\/history\/restore/);
  assert.match(app, /beforeunload/);
  assert.match(app, /articleNextAction\.addEventListener/);
  assert.match(app, /function updateArticleInspectorStatus/);
  assert.match(app, /\["info", "cover", "preview"\]/);
  assert.match(app, /\["ArrowLeft", "ArrowRight", "Home", "End"\]/);
  assert.match(app, /function renderLibraryTable/);
  assert.match(app, /libraryItemPresentation/);
  assert.match(app, /libraryTaskPresentation/);
  assert.match(app, /function setLibraryBatchMode/);
  assert.match(app, /function syncCurrentContent/);
  assert.match(app, /function renderLibraryPagination/);
  assert.match(app, /createLibrarySelection/);
  assert.match(app, /const librarySelectedItems = new Map/);
  assert.match(app, /function transitionSelectedContent/);
  assert.match(app, /let libraryUndoAvailableForFeedback = false/);
  assert.match(app, /function updateLibraryUndoVisibility/);
  assert.match(app, /libraryUndoAvailableForFeedback && lastTrashedItems\.length/);
  assert.match(app, /\{ undoTrash: result\.succeeded\.length > 0 \}/);
  assert.match(app, /function syncSelectedContent/);
  assert.match(app, /function applyBatchMetadata/);
  assert.match(app, /function trashSelectedContent/);
  assert.match(app, /function closeLibraryInspector/);
  assert.match(app, /function syncLibraryInspectorMode/);
  assert.match(app, /libraryInspector\.setAttribute\("aria-modal", "true"\)/);
  assert.match(app, /libraryMain\.inert = inspectorIsDialog/);
  assert.match(app, /event\.key === "Escape"/);
  assert.match(app, /selectAllFiltered/);
  assert.match(app, /function restoreLastTrashedDrafts/);
  assert.match(app, /function loadRecycleBin/);
  assert.match(app, /function purgeSelectedTrash/);
  assert.match(app, /\/api\/storage\/backup/);
  assert.match(app, /\/api\/recommendation-publications/);
  assert.match(app, /\/api\/content\/audit/);
  assert.match(app, /\/api\/tags\/governance/);
  assert.match(app, /\/api\/assets/);
  assert.match(app, /\/api\/storage\/dashboard/);
  assert.match(app, /\/api\/storage\/content-history\/sync/);
  assert.match(app, /openAssetLibrary\("cover"\)/);
  assert.match(app, /\/api\/history\?action=sync_content/);
  assert.match(app, /id="library-select-page"/);
  assert.match(css, /\.result\[hidden\]/);
  assert.match(css, /\.app-frame/);
  assert.match(css, /\.workspace-sidebar/);
  assert.match(css, /\.workspace-navigation/);
  assert.match(css, /min-width: 1180px/);
  assert.doesNotMatch(css, /workspace-nav-open/);
  assert.doesNotMatch(css, /@media \(max-width: 900px\)/);
  assert.doesNotMatch(css, /@media \(max-width: 560px\)/);
  assert.match(css, /\.ai-review-card/);
  assert.match(css, /\.article-audit-guidance/);
  assert.match(css, /\.title-suggestion-panel/);
  assert.match(css, /\.title-candidate-list/);
  assert.match(css, /\.publish-mode-grid/);
  assert.match(css, /\.editor-actions/);
  assert.doesNotMatch(css, /\.publish-journey/);
  assert.match(css, /\.context-action-menu/);
  assert.match(css, /\.publisher-health/);
  assert.match(css, /\.toolbar-more-menu/);
  assert.doesNotMatch(css, /\.next-step-copy/);
  assert.match(css, /\.library-tools-more/);
  assert.match(css, /\.panel\.active > \.preview/);
  assert.match(css, /\.content-table/);
  assert.match(css, /\.library-status-tabs/);
  assert.match(css, /\.library-pagination/);
  assert.match(css, /\.content-list\[data-view="compact"\]/);
  assert.match(css, /\.library-bulk-actions/);
  assert.match(css, /\.library-panel\.has-detail/);
  assert.match(css, /\.library-task-banner/);
  assert.match(css, /\.library-feedback/);
  assert.match(css, /max-height: calc\(100dvh - 32px\)/);
  assert.match(css, /\.library-next-step/);
  assert.match(css, /\.content-list:not\(\[data-batch-mode="true"\]\) \[data-batch-cell\]/);
  assert.match(css, /\.library-more-actions/);
  assert.match(css, /button\.danger/);
  assert.match(css, /\.trash-dialog/);
  assert.match(css, /\.tag-governance/);
  assert.match(css, /\.asset-library-item/);
  assert.match(css, /\.recovery-dashboard/);
  assert.match(css, /\.connection-grid/);
  assert.match(css, /\.recommendation-status/);
  assert.match(css, /\.content-state-grid/);
  assert.match(css, /\.markdown-toolbar/);
  assert.match(css, /\.library-detail-more/);
  assert.match(app, /item\.data\.draft \? "继续处理" : "编辑内容"/);
  assert.match(app, /在站点预览中查看 ↗/);
});

test("draft publishing uses explicit states, protected-branch guards, and mandatory quality checks", async () => {
  const [server, html, app, css, readme] = await Promise.all([
    read("server.js"),
    read("public/index.html"),
    read("public/app.js"),
    read("public/styles.css"),
    read("README.md"),
  ]);

  assert.doesNotMatch(html, /id="library-transition"/);
  assert.match(html, /id="article-publish-options"/);
  assert.match(html, /name="publishDateMode"/);
  assert.match(app, /function syncArticleActionState/);
  assert.match(app, /function currentArticleAuditIssues/);
  assert.match(app, /function loadSyncWorkspace/);
  assert.match(app, /function syncAllLocalContent/);
  assert.match(app, /发布草稿/);
  assert.match(app, /退回草稿/);
  assert.match(app, /api\/content\/deployment/);
  assert.match(server, /async function getFileWorkflowState/);
  assert.match(server, /async function verifyLiveContent/);
  assert.match(server, /parseFrontmatter\(markdown\)/);
  assert.match(server, /contentVerificationAnchors/);
  assert.match(server, /markdownVisibleText\(parsed\.body\)/);
  assert.match(server, /function normalizeComparableText/);
  assert.match(server, /\[\\p\{P\}\\p\{S\}\]/);
  assert.match(server, /线上已生效/);
  assert.match(server, /发布前质量检查未通过/);
  assert.match(server, /main 分支受保护/);
  assert.match(server, /function getContentWorkflowStates/);
  assert.match(server, /const searchableItems = await getContentPublicationStates\(indexedItems\)/);
  assert.match(server, /function getContentPublicationStates/);
  assert.match(server, /PublicationReceiptStore/);
  assert.match(server, /retryFailedContentSync/);
  assert.match(server, /publicationFromDeployment/);
  assert.match(server, /contentPublicationCounts/);
  assert.match(server, /function getContentGitSafety/);
  assert.match(server, /workflow\?\.state === "pending_deploy"/);
  assert.match(server, /function contentStatusCounts/);
  assert.match(server, /async function inspectBatchDrafts/);
  assert.match(server, /async function publishBatchDrafts/);
  assert.match(server, /organizeMarkdownParagraphs/);
  assert.match(server, /applyBatchParagraphSuggestion/);
  assert.match(server, /applyBatchReviewConfirmation/);
  assert.match(server, /autoOrganizeParagraphs/);
  assert.match(server, /confirmInternalReview/);
  assert.match(server, /批量发布必须使用刚刚检查过的明确内容清单/);
  assert.match(server, /expectedVersions\.get\(item\.file\)/);
  assert.match(server, /async function transitionBatchContent/);
  assert.match(server, /async function syncBatchContent/);
  assert.match(server, /async function inspectBatchSync/);
  assert.match(server, /payload\.action === "inspect-sync"/);
  assert.match(server, /isolatedContentSync/);
  assert.match(server, /auditContentLibrary/);
  assert.match(server, /function syncQueueFrom/);
  assert.match(server, /partitionSyncCandidates/);
  assert.match(server, /files: result\.synced\.map/);
  assert.match(server, /syncQueue: syncQueueFrom/);
  assert.doesNotMatch(server, /未通过上线体检，已停止同步/);
  assert.match(server, /function overlongMarkdownParagraphs/);
  assert.match(server, /请先使用“AI 整理文章资料”完成安全分段后再发布/);
  assert.match(server, /recordOperation\("sync_content"/);
  assert.match(server, /\/api\/content\/audit/);
  assert.match(server, /\/api\/history/);
  assert.match(server, /async function resolveBatchItems/);
  assert.match(server, /async function inspectBatchSelection/);
  assert.match(server, /async function updateBatchMetadata/);
  assert.match(server, /async function trashBatchDrafts/);
  assert.match(server, /async function restoreBatchDrafts/);
  assert.match(server, /async function purgeTrashItems/);
  assert.match(server, /LocalDataStore/);
  assert.match(server, /LocalContentBackup/);
  assert.match(server, /editorNote/);
  assert.match(server, /internalNote/);
  assert.match(server, /\/api\/storage\/backup/);
  assert.match(server, /\/api\/storage\/content-history\/sync/);
  assert.match(server, /\/api\/trash/);
  assert.match(server, /\/api\/content\/batch/);
  assert.match(server, /\/api\/content\/duplicate/);
  assert.match(server, /\/api\/content\/history/);
  assert.match(server, /\/api\/content\/history\/restore/);
  assert.match(server, /\/api\/assets\/upload/);
  assert.match(server, /brotliCompressSync/);
  assert.match(server, /gzipSync/);
  assert.match(server, /function safeDisplayUrl/);
  assert.match(server, /pageSize/);
  assert.match(server, /pagination:/);
  assert.match(css, /\.workflow-state/);
  assert.match(readme, /全部、草稿、本地发布、云端流程/);
  assert.match(readme, /“发布到本地”/);
  assert.match(readme, /“同步所选”/);
  assert.match(readme, /移至回收站/);
});

test("publisher writes the metadata required by Astro collections", async () => {
  const [server, html, app] = await Promise.all([read("server.js"), read("public/index.html"), read("public/app.js")]);

  assert.match(server, /sourceKind/);
  assert.match(server, /licenseUrl/);
  assert.match(server, /function normalizeImageAttribution/);
  assert.match(server, /function normalizeRecommendationGroup/);
  assert.match(server, /recommendationGroup: \$\{yamlString\(recommendationGroup\)\}/);
  assert.match(server, /user_provided/);
  assert.match(server, /群聊转存（来源待核实）/);
  assert.match(html, /name="sourceKind"/);
  assert.match(html, /name="recommendationGroup"/);
  assert.match(app, /data-import-field="recommendationGroup"/);
  assert.match(app, /请选择推荐分组/);
  assert.match(server, /公开导入前必须人工确认推荐分组/);
  assert.match(server, /公开文章必须人工确认推荐分组/);
  assert.match(html, /value="adult-humor"/);
  assert.match(html, /value="unknown"/);
  assert.match(html, /id="unknown-source-note"/);
  assert.match(html, /用户提供素材/);
  assert.match(html, /name="confirmedAt"/);
  assert.match(html, /name="licenseUrl"/);
  assert.match(server, /function inspectImageUpload/);
  assert.match(server, /PUBLISHER_MAX_IMAGE_BYTES/);
  assert.match(server, /图片文件重复/);
  assert.match(server, /409/);
  assert.doesNotMatch(html, /data-image-preview="detail"/);
  assert.doesNotMatch(html, /id="image-detail-preview"/);
  assert.match(app, /function imagePayload/);
  assert.match(app, /window\.confirm/);
  assert.match(server, /function recordUserProvidedAsset/);
  assert.match(server, /user-provided-assets\.jsonl/);
});

test("publisher imports flomo exports through a direct publish path with a draft fallback", async () => {
  const [server, importer, html, app, css, readme] = await Promise.all([
    read("server.js"),
    read("flomo-import.js"),
    read("public/index.html"),
    read("public/app.js"),
    read("public/styles.css"),
    read("README.md"),
  ]);

  assert.match(html, /data-tab="import"/);
  assert.match(html, /id="flomo-file"/);
  assert.doesNotMatch(html, /id="flomo-toggle-selection"/);
  assert.match(html, /id="flomo-selection-summary"/);
  assert.match(html, /id="flomo-only-unselected"/);
  assert.match(html, /id="flomo-review-drafts"/);
  assert.match(html, /id="flomo-publish-selected"/);
  assert.match(html, /检查并发布所选/);
  assert.match(html, /只看需处理/);
  assert.doesNotMatch(html, /id="flomo-ai-selected"/);
  assert.doesNotMatch(html, /flomo-select-ready|flomo-clear-selection/);
  assert.match(server, /\/api\/import\/flomo\/inspect/);
  assert.match(server, /\/api\/import\/flomo\/apply/);
  assert.match(server, /payload\.mode === "publish" \? "publish" : "draft"/);
  assert.match(server, /mode === "publish" && item\.status !== "ready"/);
  assert.match(server, /draft: mode !== "publish"/);
  assert.match(server, /flomo-imports\.jsonl/);
  assert.match(server, /function normalizeImportedArticle\(item, override = \{\}, \{ draft = true \} = \{\}\)/);
  assert.match(importer, /normalizeImportText/);
  assert.match(importer, /inflateRawSync/);
  assert.doesNotMatch(app, /aiOrganizeSelectedImports/);
  assert.match(app, /async function applyFlomoImport\(mode = "draft"\)/);
  assert.match(app, /async function ensureImportParagraphsBeforePublish/);
  assert.match(app, /function hasOverlongMarkdownParagraph/);
  assert.match(app, /applyFlomoImport\("publish"\)/);
  assert.match(app, /data-import-field="sourceUrl"/);
  assert.match(app, /data-import-field="source"/);
  assert.match(app, /updateFlomoSelectionToggle/);
  assert.match(app, /summarizeImportSelection/);
  assert.match(app, /organizeImportItem/);
  assert.doesNotMatch(html, /id="content-audit-format-paragraphs"/);
  assert.match(app, /async function openAuditedArticle/);
  assert.match(app, /data-audit-open-article/);
  assert.doesNotMatch(app, /打开处理 →/);
  assert.match(app, /function renderArticleAuditGuidance/);
  assert.match(html, /从内容体检带来的待处理事项/);
  assert.match(app, /contentAuditItemsByFile/);
  assert.match(app, /flomoImportFilter/);
  assert.match(app, /id="flomo-exact-duplicates"/);
  assert.match(app, /没有需要导入的内容/);
  assert.match(server, /selectedByDefault: status === "ready"/);
  assert.match(server, /sourceKind,/);
  assert.match(server, /发布后会明确显示“来源待确认”/);
  assert.match(html, /value="unknown">来源待确认/);
  assert.match(server, /importTags/);
  assert.match(app, /内部导入分组/);
  assert.match(importer, /needsSourceReview/);
  assert.match(css, /\.import-list/);
  assert.match(css, /position: sticky/);
  assert.match(css, /\.import-ai-feedback/);
  assert.match(css, /\.import-duplicates/);
  assert.match(readme, /原始 ZIP 不会保存到仓库/);
});

test("publisher keeps R2 optional and Git metadata authoritative", async () => {
  const [server, storage, envExample, readme, records] = await Promise.all([
    read("server.js"),
    read("r2-storage.js"),
    read(".env.example"),
    read("README.md"),
    read("records/README.md"),
  ]);

  assert.match(server, /ensureR2Asset/);
  assert.match(server, /r2-assets\.jsonl/);
  assert.match(server, /cloudflare-r2/);
  assert.match(storage, /memes\/\$\{hash\}/);
  assert.match(storage, /max-age=31536000, immutable/);
  assert.match(storage, /--remote/);
  assert.match(envExample, /XGIF_R2_ENABLED="false"/);
  assert.match(readme, /已有 `site\/public\/images\/memes\/` 图片不会自动迁移/);
  assert.match(records, /R2 只保存图片字节/);
});
